services:
  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: userpg
      POSTGRES_PASSWORD: passwordpg
      POSTGRES_DB: dbdev
    ports:
      - 127.0.0.1:7090:5432
    networks:
      llocal:
        aliases:
          - postgres
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2-alpine
    ports:
      - "127.0.0.1:7091:6379"
    networks:
      llocal:
        aliases:
          - redis

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: userpg
      KC_DB_PASSWORD: passwordpg
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    command:
      - start-dev
    ports:
      - "7092:8080"
    depends_on:
      - database
    networks:
      - llocal

networks:
  llocal:
    driver: bridge

volumes:
  pg_data:
    driver: local
